# Generated by Django 3.2.11 on 2022-01-13 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendHolder',
            fields=[
                ('owning_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('friends', models.ManyToManyField(related_name='_message_friendholder_friends_+', to='message.FriendHolder')),
            ],
        ),
        migrations.CreateModel(
            name='LastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('content', models.TextField()),
                ('corresponding_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corresponding_lasts', to=settings.AUTH_USER_MODEL)),
                ('pivot_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pivot_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pivot_account', 'corresponding_account')},
            },
        ),
    ]
