# Generated by Django 3.2.11 on 2022-01-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendholder',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_message_friendholder_friends_+', to='message.FriendHolder'),
        ),
    ]
